version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "${DB_PASSWORD-:CHANGE_ME}"
    MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
  panel:
    &panel-environment
    APP_URL: "https://panel.write-heberg.fr"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "Europe/Paris"
    APP_SERVICE_AUTHOR: "contact@write-heberg.fr"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@write-heberg.fr"
    MAIL_FROM_NAME: "Write Heberg' | Panel"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "writeheberg-fr01c.mail.protection.outlook.com"
    MAIL_PORT: "25"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "ssl"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:

  databases:
    image: mariadb:10.5
    container_name: Pterodactyl-DB-WRTHGB
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/data/volumes/pterodactyl/prod/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - panel

  cache:
    image: redis:alpine
    container_name: Pterodactyl-CACHE-WRTHBG
    restart: always
    networks:
      - panel

  panel:
    build:
        context: "."
        dockerfile: "./Dockerfile"
    container_name: Pterodactyl-PANEL-WRTHGB
    pull_policy: build # Portainer need it for rebuild when updating
    restart: always
    links:
      - databases
      - cache
    volumes:
      - "/data/volumes/pterodactyl/prod/www/var/:/app/var/"
      - "/data/volumes/pterodactyl/prod/www/nginx/:/etc/nginx/http.d/"
      - "/data/volumes/pterodactyl/prod/www/certs/:/etc/letsencrypt/"
      - "/data/volumes/pterodactyl/prod/www/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "databases"
      DB_PORT: "3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`panel.write-heberg.fr`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.panelhttp.rule=Host(`panel.write-heberg.fr`)"
      - "traefik.http.routers.panelhttp.entrypoints=web"
      - "traefik.http.routers.panelhttp.middlewares=redirecttohttpspanel@docker"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpspanel.loadbalancer.server.port=80"
    networks:
      - panel

  phpMyAdmin:
    image: phpmyadmin:latest
    container_name: Pterodactyl-PHPMYADMIN-WRTHBG
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - panel
    links:
      - databases
      - panel
    restart: always
    environment:
      PMA_HOSTS: NODE01-FR.WRITE-HEBERG.FR, DATABASES
      PMA_ABSOLUTE_URI: https://phpmyadmin.write-heberg.fr
      UPLOAD_LIMIT: 512M
      HIDE_PHP_VERSION: true
      MAX_EXECUTION_TIME: 600
      MEMORY_LIMIT: 256M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadminpanel.rule=Host(`phpmyadmin.write-heberg.fr`)"
      - "traefik.http.routers.phpmyadminpanel.entrypoints=websecure"
      - "traefik.http.routers.phpmyadminpanel.tls=true"
      - "traefik.http.routers.phpmyadminpanel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpmyadminpanelhttp.rule=Host(`phpmyadmin.write-heberg.fr`)"
      - "traefik.http.routers.phpmyadminpanelhttp.entrypoints=web"
      - "traefik.http.routers.phpmyadminpanelhttp.middlewares=redirecttohttpsphpmyadminpanel@docker"
      - "traefik.http.middlewares.redirecttohttpsphpmyadminpanel.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpsphpmyadminpanel.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpsphpmyadminpanel.loadbalancer.server.port=80"
    networks:
      - panel


networks:
  panel:
    name: public_wan
    external: true
