version: '3.8'
x-common:
  database:
    &db-environment
    # Do not remove the "&db-password" from the end of the line below, it is important
    # for Panel functionality.
    MYSQL_PASSWORD: &db-password "pterodactyl"
    MYSQL_ROOT_PASSWORD: "root"
  panel:
    &panel-environment
    APP_URL: "https://dev.write-heberg.fr"
    # A list of valid timezones can be found here: http://php.net/manual/en/timezones.php
    APP_TIMEZONE: "UTC"
    APP_SERVICE_AUTHOR: "noreply@example.com"
    # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
    # to generate an SSL certificate for the Panel.
    # LE_EMAIL: ""
  mail:
    &mail-environment
    MAIL_FROM: "noreply@example.com"
    MAIL_DRIVER: "smtp"
    MAIL_HOST: "mail"
    MAIL_PORT: "1025"
    MAIL_USERNAME: ""
    MAIL_PASSWORD: ""
    MAIL_ENCRYPTION: "true"

#
# ------------------------------------------------------------------------------------------
# DANGER ZONE BELOW
#
# The remainder of this file likely does not need to be changed. Please only make modifications
# below if you understand what you are doing.
#
services:
  database:
    image: mariadb:10.5
    container_name: Pterodactyl-DEV-DB-WRTHGB
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      <<: *db-environment
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
  cache:
    image: redis:alpine
    container_name: Pterodactyl-DEV-CACHE-WRTHGB
    restart: always
  panel:
    build:
        context: "."
        dockerfile: "./Dockerfile"
    container_name: Pterodactyl-DEV-PANEL-WRTHGB
    pull_policy: build # Portainer need it for rebuild when updating
    restart: always
    links:
      - database
      - cache
    volumes:
      - "/data/volumes/dev/write-heberg.fr/www/var/:/app/var/"
      - "/data/volumes/dev/write-heberg.fr/www/nginx/:/etc/nginx/http.d/"
      - "/data/volumes/dev/write-heberg.fr/www/certs/:/etc/letsencrypt/"
      - "/data/volumes/dev/write-heberg.fr/www/logs/:/app/storage/logs"
    environment:
      <<: [*panel-environment, *mail-environment]
      DB_PASSWORD: *db-password
      APP_ENV: "development"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`dev.write-heberg.fr`)"
      - "traefik.http.routers.pma.entrypoints=websecure"
      - "traefik.http.routers.pma.tls=true"
      - "traefik.http.routers.pma.tls.certresolver=myresolver"
      - "traefik.http.routers.pmahttp.rule=Host(`dev.write-heberg.fr`)"
      - "traefik.http.routers.pmahttp.entrypoints=web"
      - "traefik.http.routers.pmahttp.middlewares=redirecttohttpsdev@docker"
      - "traefik.http.middlewares.redirecttohttpspma.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpspma.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpspma.loadbalancer.server.port=80"

networks:
  PANEL-DEV:
    name: panel-dev
    external: true
