services:
  panel:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: ${CONTAINER_NAME_PANEL:-ptero-PANEL-WRTHBG}
    pull_policy: build # Portainer need it for rebuild when updating
    restart: always
    links:
      - databases
      - cache
    volumes:
      - "/data/volumes/pterodactyl/prod/www/var/:/app/var/"
      - "/data/volumes/pterodactyl/prod/www/nginx/:/etc/nginx/http.d/"
      - "/data/volumes/pterodactyl/prod/www/certs/:/etc/letsencrypt/"
      - "/data/volumes/pterodactyl/prod/www/logs/:/app/storage/logs"
    env_file: stack.env
    environment:
      APP_URL: "${APP_URL:-panel.write-heberg.fr}"
      APP_TIMEZONE: "${APP_TIMEZONE:-Europe/Paris}"
      APP_SERVICE_AUTHOR: "contact@write-heberg.fr"
      MAIL_FROM: "${MAIL_FROM:-noreply@write-heberg.fr}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME:-Panel Pterodactyl Exemple}"
      MAIL_DRIVER: "${MAIL_DRIVER:-smtp}"
      MAIL_HOST: "${MAIL_HOST:-writeheberg-fr01c.mail.protection.outlook.com}"
      MAIL_PORT: "${MAIL_PORT:-25}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION:-ssl}"
      DB_PASSWORD: "${DB_PASSWORD:-CHANGE_ME}"
      APP_ENV: "${APP_ENV:-production}"
      APP_ENVIRONMENT_ONLY: "${APP_ENVIRONMENT_ONLY:-false}"
      CACHE_DRIVER: "${CACHE_DRIVER:-redis}"
      SESSION_DRIVER: "${SESSION_DRIVER:-redis}"
      QUEUE_DRIVER: "${QUEUE_DRIVER:-redis}"
      REDIS_HOST: "${REDIS_HOST:-cache}"
      DB_HOST: "${DB_HOST:-databases}"
      DB_PORT: "${DB_PORT:-3306}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.panel.rule=Host(`${TRAEFIK_URL_PANEL:-panel.write-heberg.fr}`)"
      - "traefik.http.routers.panel.entrypoints=websecure"
      - "traefik.http.routers.panel.tls=true"
      - "traefik.http.routers.panel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.panelhttp.rule=Host(`${TRAEFIK_URL_PANEL:-panel.write-heberg.fr}`)"
      - "traefik.http.routers.panelhttp.entrypoints=web"
      - "traefik.http.routers.panelhttp.middlewares=redirecttohttpspanel@docker"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpspanel.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpspanel.loadbalancer.server.port=80"
    networks:
      - panel

  phpMyAdmin:
    image: phpmyadmin:latest
    container_name: ${CONTAINER_NAME_PMA:-ptero-PMA-WRTHBG}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - panel
    links:
      - databases
      - panel
    restart: always
    environment:
      PMA_HOSTS: ${PMA_HOSTS:-NODE01-FR.WRITE-HEBERG.FR, DATABASES}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI:-https://pma.write-heberg.fr}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT:-512M}
      HIDE_PHP_VERSION: ${HIDE_PHP_VERSION:-true}
      MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME:-600}
      MEMORY_LIMIT: ${MEMORY_LIMIT:-256M}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadminpanel.rule=Host(`${TRAEFIK_URL_PMA:-pma.write-heberg.fr}`)"
      - "traefik.http.routers.phpmyadminpanel.entrypoints=websecure"
      - "traefik.http.routers.phpmyadminpanel.tls=true"
      - "traefik.http.routers.phpmyadminpanel.tls.certresolver=letsencrypt"
      - "traefik.http.routers.phpmyadminpanelhttp.rule=Host(`${TRAEFIK_URL_PMA:-pma.write-heberg.fr}`)"
      - "traefik.http.routers.phpmyadminpanelhttp.entrypoints=web"
      - "traefik.http.routers.phpmyadminpanelhttp.middlewares=redirecttohttpsphpmyadminpanel@docker"
      - "traefik.http.middlewares.redirecttohttpsphpmyadminpanel.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecttohttpsphpmyadminpanel.redirectscheme.permanent=true"
      - "traefik.http.services.redirecttohttpsphpmyadminpanel.loadbalancer.server.port=80"
    networks:
      - panel

  databases:
    image: mariadb:10.5
    container_name: ${CONTAINER_NAME_DB:-ptero-DB-WRTHBG}
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/data/volumes/pterodactyl/prod/database:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD:-CHANGE_ME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-panel}"
      MYSQL_USER: "${MYSQL_USER:-pterodactyl}"
    networks:
      - panel

  cache:
    image: redis:alpine
    container_name: ${CONTAINER_NAME_CACHE:-ptero-CACHE-WRTHBG}
    restart: always
    networks:
      - panel

networks:
  panel:
    name: ${NAME_NETWORK:-public_wan}
    external: true
